### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by BearToCode** [ISibboI/evalexpr#109]
The title says it all. It would be cool!

**Comment by ISibboI** [comment]
Hi, I am sorry but this would be out of scope for this crate. So I will at least not implement it myself. However, I would be willing to accept a pull request. But, we should first talk about the design of the implementation. I am e.g. unsure about making `i` a keyword, since it is also often used as variable name.

**Comment by BearToCode** [comment]
I understand, and introducing it would also not be easy... I'm currently not interested on working on it personally, so I guess you can close the issue if you like. It was just a feature I would have appreciated. Anyway, that's a great tool!

**Comment by ISibboI** [comment]
Alright, then I'll close this for now.
