### ISSUE TITLE
Implicit multiplication support

### ISSUE THREAD

**Issue by Titaniumtown** [ISibboI/evalexpr#97]
Just came across this project, but it doesn't seem to have support for something like
```rust
let precompiled = build_operator_tree("2x").unwrap();

let context: HashMapContext = context_map! {
    "x" => x,
}.unwrap();

precompiled.eval_with_context(&context).unwrap().as_number().unwrap()
```
The key here being that `2x` is not interpreted as `2*x`. Could this functionality be included in the future? Thanks!

**Comment by ISibboI** [comment]
Hi, thank you for your idea. If I am not mistaken, what you are asking for is unfortunately very hard. Writing two non-operator tokens after each other makes the first one a function that is called with the second as argument at the moment. If the first token is an identifier, and that identifier happens to be both a variable and a function in the given context, then the evaluation would be ambiguous. I would like to avoid having more complicated rules about evaluation, since evalexpr is meant to be simple and its inputs to be readable for people who do not know any details.
Additionally, the problem solved does not seem crucial to me, as it is not much work to write `2 * x` instead of `2x`.

So unfortunately, I need to deny this feature request.
